### ISSUE TITLE
Not able to run on HTTP informer

### ISSUE THREAD

**Issue by sanjaybharkatiya** [lalitpagaria/obsei#100]
**Describe the bug**
I have created a mock server on local which is running .
but while running OBSEI using HTTP i am getting below response

(HTTPSConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /test (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))))

**Comment by lalitpagaria** [comment]
@sanjaybharkatiya can you please pull latest changes and test
