### ISSUE TITLE
[BUG] mypy: Found 126 errors in 26 files (checked 44 source files) 

### ISSUE THREAD

**Issue by shahrukhx01** [lalitpagaria/obsei#121]
**Describe the bug**
Mypy found 126 errors in 26 files (checked 44 source files)

**To Reproduce**
Steps to reproduce the behavior: run the following command
```bash
mypy obsei/ --ignore-missing-imports
```
**Expected behavior**
No mypy errors should be there.

**Comment by lalitpagaria** [comment]
Thanks for adding this.

**Comment by lalitpagaria** [comment]
Closed with #125
