### ISSUE TITLE
Add Facebook Observer/Source

### ISSUE THREAD

**Issue by lalitpagaria** [lalitpagaria/obsei#16]

**Comment by lalitpagaria** [comment]
- Page comments
- Hashtag search
- Search query
- Someone tag user

**Comment by GirishPatel** [comment]
Need to support posts comments in page.
Argument:
1. No of post to scrape.
2. Comments of post.
3. Filter comment based on some parameter.

Output of source:
1. Flattered list of all comments irrespective of post and comment tree.

Post which are tags for given page.

**Comment by lalitpagaria** [comment]
Fixed by #150
