### ISSUE TITLE
Add DAG support and fix inconsistent naming

### ISSUE THREAD

**Issue by lalitpagaria** [lalitpagaria/obsei#8]
- [ ] Introduce DAG based workflow. Need to finalise between [networkx](https://github.com/networkx/networkx) or [airflow](https://airflow.apache.org/docs/apache-airflow/stable/concepts.html)
- [ ] Replace use of `Sink` with `Informer` (packages, classes and variables)
- [ ] Replace use of `Source` with `Observer` (packages, classes and variables)
- [ ] Replace use of `Analyzer` with `Segmenter` (packages, classes and variables)
- [ ] Add `BaseSegmenter` class
- [ ] Fix state store
- [ ] Fix circular dependency in Workflow classes

**Comment by shahrukhx01** [comment]
@lalitpagaria  for this point "Introduce DAG based workflow. Need to finalise between networkx or airflow" please do let me know when you plan to start this implementation, as I'm seriously interested in working on this feature, as it'd also help me understand Haystack's codebase. thanks!

**Comment by lalitpagaria** [comment]
@shahrukhx01 When I created this ticket and now I encountered many different ways to solve it. Each have some pros and some cons. Ideally I would like to build this feature such that we can plug any framework, because it directly linked to production deployment. Currently our target to build good user base who try Obsei and once it build then we can think about it that is the reason for lowest priority.
Few things we considered -
1. Ray
2. temporal
3. airflow
4. networkx
5. containers (similar to what Jina does)
and many more.

If you have any suggestion regarding how we can abstract it then it would be great.
I am adding @GirishPatel to this conversation as well.

**Comment by lalitpagaria** [comment]
Our aim to build NLP based open source workflows like https://github.com/n8n-io/n8n
Currently we supporting text but there is plan to support image and audio based workflows.
But we are very far from it. But hoping one day we can achieve this target 😅🐢

**Comment by shahrukhx01** [comment]
eventually, we'll get there!

**Comment by lalitpagaria** [comment]
Closing this and moving discussion to https://github.com/lalitpagaria/obsei/issues/145
