### ISSUE TITLE
Batch call to pipeline in Analyzers

### ISSUE THREAD

**Issue by GirishPatel** [lalitpagaria/obsei#88]
**Is your feature request related to a problem? Please describe.**
Currently analyzers are iterating over array and calling pipeline method with single argument. This can be improve upon by calling pipeline with array of data.

**Describe the solution you'd like**
Divide input array into multiple batches and pass batch array to pipeline. Also, do performance analysis if this improves library latency.

**Comment by shahrukhx01** [comment]
@lalitpagaria I think here we can use PyTorch data loaders, it'd elegantly batch data for us.

**Comment by lalitpagaria** [comment]
@shahrukhx01 If I am correct, you are talking about this https://pytorch.org/docs/stable/data.html ?
But it will add dependency to pytorch for other parts like source, sink and few simple non transformers based analyzer.
How about using simple solution like following -
https://stackoverflow.com/questions/8290397/how-to-split-an-iterable-in-constant-size-chunks

Also currently in analyzers we are calling transformers pipeline for single text sequentially. But few pipeline support list[str] so we can leverage transformers internal batching as well.

**Comment by shahrukhx01** [comment]
@lalitpagaria yes, if that's the case then we can go with the plain pythonic implementation, as long as you don't have any plans to add automated model retraining/finetuning, then such implementation can come handy, otherwise, what you suggested fits our requirement.

**Comment by lalitpagaria** [comment]
There are plans to add automated model retraining/finetuning but they will be outside of Obsei. Idea to keep isolation between model serving part and training/finetuning part. First we might need to think how to collect feedback about model prediction automatically from the user.

For now we can go ahea with pythonic implementation.

**Comment by shahrukhx01** [comment]
@lalitpagaria  Could you please confirm which of the following analyzers need this change? Since, this won't take much I'll create a quick PR on this based on the pythonic approach
1. base_analyzer.py
2. classification_analyzer.py
3. dummy_analyzer.py
4. ner_analyzer.py
5. pii_analyzer.py
6. sentiment_analyzer.py
7. translation_analyzer.py

**Comment by lalitpagaria** [comment]
Almost all as each receive list as input. Just to make sure `batch_size` input param should be configurable.
