### ISSUE TITLE
Not able to build Obsei in Windows machine using pip install [BUG]

### ISSUE THREAD

**Issue by sanjaybharkatiya** [lalitpagaria/obsei#93]
**Describe the bug**

While building Obsei using pip , its continuously failing while building uvloop-0.15.2.tar.gz

**To Reproduce**
pip install obsei in windows 7/10 machine
**Expected behavior**
Should build successfully  
**Stacktrace**
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\sanjay.bharkatiya\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sanjay.bharkatiya\\AppData\\Local\\Temp\\pip-install-fumhr70o\\uvloop\\setup.py'"'"'; __file__='"'"'C:\\Users\\sanjay.bharkatiya\\AppData\\Local\\Temp\\pip-install-fumhr70o\\uvloop\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sanjay.bharkatiya\AppData\Local\Temp\pip-pip-egg-info-993ebv1w'
         cwd: C:\Users\sanjay.bharkatiya\AppData\Local\Temp\pip-install-fumhr70o\uvloop\
    Complete output (15 lines):
    Error processing line 1 of c:\users\sanjay.bharkatiya\appdata\local\programs\python\python39\lib\site-packages\matplotlib-3.4.1-py3.9-nspkg.pth:

      Traceback (most recent call last):
        File "c:\users\sanjay.bharkatiya\appdata\local\programs\python\python39\lib\site.py", line 169, in addpackage
          exec(line)
        File "<string>", line 1, in <module>
        File "<frozen importlib._bootstrap>", line 562, in module_from_spec
      AttributeError: 'NoneType' object has no attribute 'loader'

    Remainder of file ignored
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sanjay.bharkatiya\AppData\Local\Temp\pip-install-fumhr70o\uvloop\setup.py", line 8, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Please complete the following information:**
 - OS:
 - Version:

**Additional context**

**Comment by lalitpagaria** [comment]
Thanks for reporting it @sanjaybharkatiya 
Please try master branch by loading as follows -
```
pip install git+git://github.com/lalitpagaria/obsei@master#egg=obsei
```

**Comment by sanjaybharkatiya** [comment]
@lalitpagaria Thanks for above fix , Now its failing with 

ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cpu (from obsei) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==1.8.1+cpu (from obsei)

My GPU :  Intel UHD Graphics 620
OS: Windows 10 64 bit

Pip Command  = pip install git+git://github.com/lalitpagaria/obsei@master#egg=obsei

**Comment by lalitpagaria** [comment]
@sanjaybharkatiya Can you please try again. It seem torch is not fully supported on Intel GPUs.
I have made torch installation on windows manually. Can you please install Obsei as follows -
```
# To install latest Obsei
pip install git+git://github.com/lalitpagaria/obsei@master#egg=obsei
# To install torch on windows (If not GPU)
pip install torch==1.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
# To install torch on windows (if GPU present)
pip install torch==1.8.1-f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by sanjaybharkatiya** [comment]
@lalitpagaria Thanks for the Fix , its working now .
